# Generated by Django 4.2.1 on 2023-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default='Null', max_length=20)),
                ('name', models.CharField(default='Null', max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mobileno', models.IntegerField()),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
