# Generated by Django 4.2.1 on 2023-09-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0002_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='type',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
