# Generated by Django 4.2.1 on 2023-09-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0003_alter_contact_us_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contact_us_data',
        ),
    ]
