# Generated by Django 4.2.1 on 2023-09-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0005_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='admin_id',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
    ]
