# Generated by Django 4.2.1 on 2023-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0006_alter_admins_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('mobileno', models.IntegerField()),
                ('app_date', models.DateField()),
                ('symptoms', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
