# Generated by Django 4.2.1 on 2023-09-13 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0007_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 9, 13)),
        ),
    ]
