# Generated by Django 4.2.1 on 2023-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0008_patients_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='dob',
        ),
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
