# Generated by Django 4.2.1 on 2023-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0009_remove_patients_dob_patients_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
