# Generated by Django 4.2.1 on 2023-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0012_alter_patients_app_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='discharged_patients',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('mobileno', models.IntegerField()),
                ('age', models.IntegerField(default=0)),
                ('app_date', models.CharField(default='2023-09-20', max_length=20)),
                ('discharged_date', models.CharField(default='2023-09-20', max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(default='null', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-09-20', max_length=20),
        ),
    ]
