# Generated by Django 4.2.1 on 2023-09-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0013_discharged_patients_alter_patients_app_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discharged_patients',
            old_name='discharged_date',
            new_name='dis_date',
        ),
    ]
