# Generated by Django 4.2.1 on 2023-09-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0015_alter_discharged_patients_app_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
