# Generated by Django 4.2.1 on 2023-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0017_alter_discharged_patients_app_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='image',
            field=models.ImageField(default='null', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-09-29', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-09-29', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-09-29', max_length=20),
        ),
    ]
