# Generated by Django 4.2.1 on 2023-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0018_patients_image_alter_discharged_patients_app_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharged_patients',
            name='image',
            field=models.ImageField(default='null', null=True, upload_to='images/'),
        ),
    ]
