# Generated by Django 4.2.1 on 2023-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0019_discharged_patients_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(default='null', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-09-30', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-09-30', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-09-30', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='mobileno',
            field=models.IntegerField(null=True),
        ),
    ]
