# Generated by Django 4.2.1 on 2023-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0021_appointment_alter_discharged_patients_app_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-02', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-02', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-02', max_length=20),
        ),
    ]
