# Generated by Django 4.2.1 on 2023-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0022_doctors_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='approve_doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='null', max_length=40)),
                ('lastname', models.CharField(default='null', max_length=40)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('experience', models.IntegerField(default=None, null=True)),
                ('image', models.ImageField(default='null', null=True, upload_to='images/')),
                ('application_date', models.CharField(default='null', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
