# Generated by Django 4.2.1 on 2023-10-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0025_alter_discharged_patients_app_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
