# Generated by Django 4.2.1 on 2023-10-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0025_departments_appointment_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department', models.CharField(default='Cardiologist', max_length=70, primary_key=True, serialize=False)),
            ],
        ),
    ]
