# Generated by Django 4.2.1 on 2023-10-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0026_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
