# Generated by Django 4.2.1 on 2023-10-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0027_appointment'),
        ('HospitalManagement', '0029_delete_departments'),
    ]

    operations = [
    ]
