# Generated by Django 4.2.1 on 2023-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0030_merge_0027_appointment_0029_delete_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department', models.CharField(default='Cardiologist', max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-05', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-05', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-05', max_length=20),
        ),
    ]
