# Generated by Django 4.2.1 on 2023-10-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0033_remove_appointment_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
