# Generated by Django 4.2.1 on 2023-10-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0035_departments_appointment_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_created',
            new_name='date',
        ),
    ]
