# Generated by Django 4.2.1 on 2023-10-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0037_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('symptoms', models.CharField(max_length=400, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagement.departments')),
            ],
        ),
    ]
