# Generated by Django 4.2.1 on 2023-10-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0038_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-09', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-09', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-09', max_length=20),
        ),
    ]
