# Generated by Django 4.2.1 on 2023-10-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0041_delete_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorreg',
            fields=[
                ('doctor_id', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='null', max_length=40)),
                ('lastname', models.CharField(default='null', max_length=40)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('experience', models.IntegerField(default=None, null=True)),
                ('image', models.ImageField(default='null', null=True, upload_to='images/')),
                ('age', models.IntegerField(default=0, null=True)),
                ('date', models.CharField(default='null', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagement.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Patientreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagement.patientreg')),
            ],
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
        migrations.RenameField(
            model_name='approve_doctors',
            old_name='application_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='approve_doctors',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='approve_doctors',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagement.departments'),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-15', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-15', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-15', max_length=20),
        ),
    ]
