# Generated by Django 4.2.1 on 2023-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0042_doctorreg_patientreg_reporthistory_delete_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
