# Generated by Django 4.2.1 on 2023-10-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0045_appointment_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='blood_group',
        ),
    ]
