# Generated by Django 4.2.1 on 2023-10-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0046_remove_appointment_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='approve_doctors',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctorreg',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='department',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
