# Generated by Django 4.2.1 on 2023-10-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0049_appointment_department_approve_doctors_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve_doctors',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='firstname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='lastname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='mobile',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='approve_doctors',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-16', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-16', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='date',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='firstname',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='lastname',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='mobile',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-16', max_length=20),
        ),
    ]
