# Generated by Django 4.2.1 on 2023-10-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0050_alter_approve_doctors_age_alter_approve_doctors_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approve_doctors',
            name='gender',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='discharged_patients',
            name='gender',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='gender',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-17', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-17', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-17', max_length=20),
        ),
    ]
