# Generated by Django 4.2.1 on 2023-10-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0052_feedback_data_delete_contact_us_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve_doctors',
            name='qualification',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='qualification',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-18', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-18', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-18', max_length=20),
        ),
    ]
