# Generated by Django 4.2.1 on 2023-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0053_approve_doctors_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
