# Generated by Django 4.2.1 on 2023-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0056_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_data',
            name='mobileno',
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-20', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-20', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-20', max_length=20),
        ),
    ]
