# Generated by Django 4.2.1 on 2023-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0058_patients_doctor_alter_discharged_patients_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discharged_patients',
            name='address',
        ),
        migrations.RemoveField(
            model_name='discharged_patients',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='discharged_patients',
            name='discharge_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
