# Generated by Django 4.2.1 on 2023-10-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0059_remove_discharged_patients_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discharged_patients',
            name='image',
        ),
    ]
