# Generated by Django 4.2.1 on 2023-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0061_delete_discharged_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='discharged_patients',
            fields=[
                ('discharge_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('mobileno', models.IntegerField()),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='Male', max_length=10, null=True)),
                ('app_date', models.CharField(default='2023-10-20', max_length=20)),
                ('dis_date', models.CharField(default='2023-10-20', max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('description', models.CharField(default='null', max_length=100, null=True)),
            ],
        ),
    ]
