# Generated by Django 4.2.1 on 2023-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0062_discharged_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharged_patients',
            name='app_or_pat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='app_date',
            field=models.CharField(default='2023-10-22', max_length=20),
        ),
        migrations.AlterField(
            model_name='discharged_patients',
            name='dis_date',
            field=models.CharField(default='2023-10-22', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='app_date',
            field=models.CharField(default='2023-10-22', max_length=20),
        ),
    ]
