# Generated by Django 4.2.1 on 2023-10-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0064_discharged_patients_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discharged_patients',
            name='department',
        ),
    ]
